export const TOPIC = {
  id: "coastline-ranking",
  titleTop: "FIVE COASTLINES",
  titleBottom: "THAT HIDE THE PORT STORY",
  openerSub: "EDITORIAL RANKING / COASTAL GEOGRAPHY",
  deskName: "GREEN GLOBE / SPECIAL",
  edition: "12 AUG 2026",
  duration: 60,
  chapters: [
    {
      id: "finland",
      rank: 5,
      code: "FI",
      country: "FINLAND",
      coordinates: [26, 64],
      kicker: "RANK 05 / ICE WINDOW",
      headline: "COASTAL WATERS FREEZE IN WINTER",
      detail: "A shorter shipping window — and icebreaking as routine infrastructure.",
      captionPlain: "COASTAL WATERS",
      captionAccent: "FREEZE IN WINTER",
      mapSource: "Finnish Meteorological Institute / Baltic sea ice",
      script: "Number five is Finland. Parts of the Baltic freeze in winter, narrowing the shipping season and making icebreaking part of ordinary trade.",
    },
    {
      id: "suriname",
      rank: 4,
      code: "SR",
      country: "SURINAME",
      coordinates: [-56, 4],
      kicker: "RANK 04 / MUD COAST",
      headline: "A SHIFTING ATLANTIC SHORE",
      detail: "Mudflats, wetlands, and mangroves complicate big port construction.",
      captionPlain: "A SHIFTING",
      captionAccent: "MUDDY SHORE",
      mapSource: "UNFCCC / Suriname national communication",
      script: "Number four is Suriname. Its Atlantic shore is shaped by mudflats, wetlands, and mangroves, a shifting coast that complicates big port construction.",
    },
    {
      id: "namibia",
      rank: 3,
      code: "NA",
      country: "NAMIBIA",
      coordinates: [17, -22],
      kicker: "RANK 03 / DESERT EDGE",
      headline: "DUNES MEET THE ATLANTIC",
      detail: "The Namib runs beside the sea, leaving long stretches of coast remote from inland routes.",
      captionPlain: "DUNES MEET",
      captionAccent: "THE ATLANTIC",
      mapSource: "NASA / UNESCO Namib Sand Sea",
      script: "Number three is Namibia. The Namib Desert runs along the Atlantic, so long stretches of coast meet dunes and fog before they meet easy inland access.",
    },
    {
      id: "russia",
      rank: 2,
      code: "RU",
      country: "RUSSIA",
      coordinates: [100, 60],
      kicker: "RANK 02 / ICE LOCK",
      headline: "A LONG COAST LOCKED BY ICE",
      detail: "The Arctic shore is ice-constrained for part of the year; southern ports still do practical work.",
      captionPlain: "A LONG COAST",
      captionAccent: "LOCKED BY ICE",
      mapSource: "Arctic sea-ice / Northern Sea Route reporting",
      script: "Number two is Russia. The coastline is enormous, but much of the Arctic shore is ice-constrained for part of the year. Southern ports still do much of the practical work.",
    },
    {
      id: "bosnia",
      rank: 1,
      code: "BA",
      country: "BOSNIA AND HERZEGOVINA",
      coordinates: [18, 44],
      kicker: "RANK 01 / NARROW OUTLET",
      headline: "COASTLINE: YES. ACCESS: COMPLICATED.",
      detail: "A tiny Adriatic outlet at Neum, boxed in by Croatia.",
      captionPlain: "COASTLINE: YES.",
      captionAccent: "EASY ACCESS: NO.",
      mapSource: "Bosnia and Herzegovina / Neum coastal geography",
      script: "And number one is Bosnia and Herzegovina. Its tiny Adriatic outlet at Neum is boxed in by Croatia, making a short coastline feel even less connected to the wider sea.",
    },
  ],
  closer: {
    title: "THE MAP HIDES THE PORT STORY",
    sub: "Coastline is not the same as access.",
  },
};

export const NARRATION_SEGMENTS = [
  {
    id: "opener",
    script: "A coast can look powerful. But ice, mud, sand, and borders can make it hard to use.",
  },
  ...TOPIC.chapters.map((chapter) => ({
    id: chapter.id,
    script: chapter.script,
  })),
];
